routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['prefix'=>'admin','namespace'=>'Admin', 'middleware' => ['admin']],function(){
    Route::get('home', 'AdminController@home');
    Route::resource('posts', 'PostController');
    Route::get('posts-show', 'PostController@anyDatatables')->name('datatable_post');
    Route::get('posts-visiable', 'PostController@visiable')->name('visable_post');
    Route::get('posts-indexhot', 'PostController@indexHot')->name('index_hot');

    Route::resource('comments', 'CommentController');
    Route::get('comments-show', 'CommentController@anyDatatables')->name('datatable_comment');

    Route::resource('products', 'ProductController');
    Route::get('products-show', 'ProductController@anyDatatables')->name('datatable_product');

    Route::resource('contact', 'ContactController');
    Route::resource('book', 'BookController');
    Route::get('export-books', 'BookController@exportToExcel')->name('exportBooks');

    Route::resource('templates', 'TemplateController');
    Route::resource('type-information', 'TypeInformationController');
    Route::resource('type-input', 'TypeInputController');
    Route::resource('type-sub-post', 'TypeSubPostController');
    Route::resource('categories', 'CategoryController');
    Route::resource('category-products', 'CategoryProductController');
    Route::group(['prefix' => '{typePost}'], function($typePost){
        // Files
        Route::resource('sub-posts', 'SubPostController');
        Route::get('sub-posts-show', 'SubPostController@anyDatatables')->name('datatable_sub_posts');
    });
    Route::resource('information', 'InformationController', ['only' => [
        'index', 'store'
    ]]);
    Route::resource('menus', 'MenuController');
    Route::resource('users', 'UserController');
    

    Route::resource('subcribe-email', 'SubcribeEmailController');
    Route::get('subcribe-email-anyDatabase', 'SubcribeEmailController@anyDatatables')->name('subcribe-email-data');
    Route::post('group-mail/create', 'GroupMailController@store')->name('group_mail.create');
    Route::delete('group-mail/{groupMail}', 'GroupMailController@destroy')->name('group_mail.destroy');
    Route::post('send-mail', 'SubcribeEmailController@send')->name('subcribe-email_send');
    Route::get('export-email', 'SubcribeEmailController@exportToExcel')->name('exportEmail');

    Route::get('hinh-thuc-thanh-toan', 'OrderController@setting')->name('method_payment');
    Route::post('cap-nhat-ngan-hang', 'OrderController@updateBank')->name('bank');
    Route::post('cap-nhat-ma-giam-gia', 'OrderController@updateCodeSale')->name('code_sale');
    Route::post('cap-nhat-phi-ship', 'OrderController@updateShip')->name('cost_ship');
    Route::post('cap-nhat-tinh-diem', 'OrderController@updateSetting')->name('updateSetting');

    Route::get('don-hang', 'OrderController@listOrder')->name('orderAdmin');
    Route::delete('don-hang/{order}', 'OrderController@deleteOrder')->name('orderAdmin.destroy');

    Route::post('cap-nhat-trang-thai-don-hang', 'OrderController@updateStatusOrder')->name('orderUpdateStatus');

    //quản lý vé
    Route::get('quan-ly-ve', 'VeController@index')->name('ql_ve');
    Route::get('ve-show', 'VeController@anyDatatables')->name('datatable_ve');
    Route::get('add-ve', 'VeController@add')->name('them_ve');
    Route::post('add-ve', 'VeController@store')->name('luu_ve');
    Route::get('edit-ve/{id}', 'VeController@edit')->name('edit_ve');
    Route::post('update-ve/{id}', 'VeController@update')->name('sua_ve');
    Route::get('delete-ve/{id}', 'VeController@destroy')->name('xoa_ve');

    //quản lý tau
    Route::get('quan-ly-tau', 'TauController@index')->name('ql_tau');
    Route::get('tau-show', 'TauController@anyDatatables')->name('datatable_tau');
    Route::get('add-tau', 'TauController@add')->name('them_tau');
    Route::post('add-tau', 'TauController@store')->name('luu_tau');
    Route::get('edit-tau/{id}', 'TauController@edit')->name('edit_tau');
    Route::post('update-tau/{id}', 'TauController@update')->name('sua_tau');
    Route::get('delete-tau/{id}', 'TauController@destroy')->name('xoa_tau');

     //quản lý tau
     Route::get('quan-ly-gio-tau', 'GioTauController@index')->name('ql_gio_tau');
     Route::get('gio-tau-show', 'GioTauController@anyDatatables')->name('datatable_gio_tau');
     Route::get('add-gio-tau', 'GioTauController@add')->name('them_gio_tau');
     Route::post('add-gio-tau', 'GioTauController@store')->name('luu_gio_tau');
     Route::get('edit-gio-tau/{id}', 'GioTauController@edit')->name('edit_gio_tau');
     Route::post('update-gio-tau/{id}', 'GioTauController@update')->name('sua_gio_tau');
     Route::get('delete-gio-tau/{id}', 'GioTauController@destroy')->name('xoa_gio_tau');

     //quản lý diem dung
     Route::get('quan-ly-diem-dung', 'DiemDungController@index')->name('ql_diem_dung');
     Route::get('diem-dung-show', 'DiemDungController@anyDatatables')->name('datatable_diem_dung');
     Route::get('add-diem-dung', 'DiemDungController@add')->name('them_diem_dung');
     Route::post('add-diem-dung', 'DiemDungController@store')->name('luu_diem_dung');
     Route::get('edit-diem-dung/{id}', 'DiemDungController@edit')->name('edit_diem_dung');
     Route::post('update-diem-dung/{id}', 'DiemDungController@update')->name('sua_điem_dung');
     Route::get('delete-diem-dung/{id}', 'DiemDungController@destroy')->name('xoa_diem_dung');
 

    //quản lý giao dich
    Route::get('quan-ly-giao-dich', 'GiaoDichController@index')->name('ql_giao_dich');
    Route::get('giao-dich-show', 'GiaoDichController@anyDatatables')->name('datatable_giao_dich');
    Route::get('add-giao-dich', 'GiaoDichController@add')->name('them_giao_dich');
    Route::post('add-giao-dich', 'GiaoDichController@store')->name('luu_giao_dich');
    Route::get('edit-giao-dich/{id}', 'GiaoDichController@edit')->name('edit_giao_dich');
    Route::post('update-giao-dich/{id}', 'GiaoDichController@update')->name('sua_giao_dich');
    Route::get('delete-giao-dich/{id}', 'GiaoDichController@destroy')->name('xoa_giao_dich');

    //quản lý Thanh toan
    Route::get('quan-li-thanh-toan', 'ThanhToanController@index')->name('ql_thanh_toan');
    Route::get('thanh-toan-show', 'ThanhToanController@anyDatatables')->name('datatable_thanh_toan');
    Route::get('add-thanh-toan', 'ThanhToanController@add')->name('them-thanh_toan');
    Route::post('add-thanh-toan', 'ThanhToanController@store')->name('luu_thanh_toan');
    Route::get('edit-thanh-toan/{id}', 'ThanhToanController@edit')->name('edit_thanh_toan');
    Route::post('update-thanh-toan/{id}', 'ThanhToanController@update')->name('sua_thanh_toan');
    Route::get('delete-thanh-toan/{id}', 'ThanhToanController@destroy')->name('xoa_thanh_toan');

    //quản lý Thanh toan
    Route::get('quan-li-khach-hang', 'KhachHangController@index')->name('ql_khach_hang');
    Route::get('khach-hang-show', 'KhachHangController@anyDatatables')->name('datatable_khach_hang');
    Route::get('add-khach-hang', 'KhachHangController@add')->name('them_khach_hang');
    Route::post('add-khach-hang', 'KhachHangController@store')->name('luu_khach_hang');
    Route::get('edit-khach-hang/{id}', 'KhachHangController@edit')->name('edit_khach_hang');
    Route::post('update-khach-hang/{id}', 'KhachHangController@update')->name('sua_khach_hang');
    Route::get('delete-khach-hang/{id}', 'KhachHangController@destroy')->name('xoa_khach_hang');

    //ajax don hang
    Route::get('xac-nhan-don-hang', 'ThanhToanController@submitOrder')->name('xac_nhan_don_hang');
    Route::get('huy-don-hang', 'ThanhToanController@cancelOrder')->name('huy_don_hang');



});
//dang nhap
Route::group(['prefix'=>'admin', 'namespace'=>'Admin' ],function(){
    Route::get('/','LoginController@showLoginForm');
    Route::get('login','LoginController@showLoginForm')->name('login');
    Route::post('login','LoginController@login');
    Route::get('logout','LoginController@logout');
    Route::post('logout','LoginController@logout')->name('logout');
    //reset password
    Route::get('password/reset','LoginController@getReset');
    Route::post('password/reset','LoginController@postReset');
});

Route::group(['namespace'=>'Site'], function() {
    Route::get('/', 'HomeController@index')->name('home');
    Route::post('ngon-ngu', 'LanguageController@index')->name('change_language');
    //Tìm kiếm chuyến tàu 
    Route::post('/tim-tau','TimTauController@find')->name('tim_tau');
    //show chuyến tàu
    Route::get('/chi-tiet-tau/{id}/{gaDi}','TimTauController@detail')->name('chi_tiet_tau');
    //đặt hàng
    Route::post('dat-hang','TimTauController@order')->name('dat_hang');


});
Route::group(['prefix'=> '{languageCurrent}', 'namespace'=>'Site'], function( $languageCurrent) {
    Route::get('/', 'HomeController@index')->name('home');

 //   Route::get('/tim-kiem', 'ProductCategoryController@search')->name('search_product');
  //  Route::get('/tim-kiem-ajax', 'ProductCategoryController@searchAjax')->name('search_product_ajax');
 //   Route::get('rating', 'ProductController@Rating')->name('rating');
    Route::get('/tim-kiem', 'ProductCategoryController@search')->name('search');

    Route::get('/dang-ky','RegisterController@showRegistrationForm')->name('register');
    Route::post('/dang-ky','RegisterController@register');

    Route::post('/quen-mat-khau','PersonController@forgetPassword')->name('forget_password');
    Route::post('/dang-nhap','LoginController@login');
    Route::get('dang-xuat','LoginController@logout')->name('logoutHome');
    Route::post('dang-xuat','LoginController@logout');

resources/views/admin/partials/index_hot.blade.php
<!-- Modal -->
<div class="modal fade" id="myModalIndexhot" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content_1">
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
            </div>
        </div>
    </div>
</div>
<script>
    function changeIndexHot(e) {
        var postId = $(e).attr('postId');
        var index = 0;
        if ($(e).prop('checked')) {
            index = 1;
        }

        $.ajax({
            type: "GET",
            url: '{!! route('index_hot') !!}',
            data: {
                post_id: postId,
                index_hot: index
            },
            success: function(data){
                $('#myModalIndexhot .modal-body').empty();
                if (index == 0) {
                    $('#myModalIndexhot .modal-body').append('Ẩn');
                    $('#myModalIndexhot').modal('show');

                    return true;
                }
                $('#myModalIndexhot .modal-body').append('Hiện');
                $('#myModalIndexhot').modal('show');

                return true;
            }
        });
        return true;
    }
</script>
<style>
    .modal-content_1 {
        background: #fff;
    }
</style>

resources/views/admin/partials/nav.blade.php
<header class="main-header">
    <!-- Logo -->
    <a href="index2.html" class="logo">
        <!-- mini logo for sidebar mini 50x50 pixels -->
        <span class="logo-mini"><b>A</b>LT</span>
        <!-- logo for regular state and mobile devices -->
        <span class="logo-lg"><b>Quản trị</b> website</span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
        <!-- Sidebar toggle button-->
        <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <!-- User Account: style can be found in dropdown.less -->
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="{{ asset(Auth::user()->image) }}" class="user-image" alt="User Image">
                        <span class="hidden-xs">{{Auth::user()->name}}</span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- User image -->
                        <li class="user-header">
                            <img src="{{ asset(Auth::user()->image) }}" class="img-circle" alt="User Image">

                            <p>
                                {{Auth::user()->name}}
                                <small>{{Auth::user()->email}}</small>
                                <small>{{Auth::user()->phone}}</small>
                            </p>
                        </li>
                        <!-- Menu Footer-->
                        <li class="user-footer">
                            <div class="pull-left">
                                <a href="#" class="btn btn-default btn-flat">Thông tin</a>
                            </div>
                            <div class="pull-right">
                                <a class="btn btn-default btn-flat" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">Đăng suất</a>
                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    {{ csrf_field() }}
                                </form>
                            </div>
                        </li>
                    </ul>
                </li>
                <!-- Control Sidebar Toggle Button -->
            </ul>
        </div>
    </nav>
</header>

resources/views/admin/partials/popup_delete.blade.php
<!-- Modal -->
<div class="modal fade" id="myModalDelete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content_1">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Bạn có chắc chắn muốn xóa?</h4>
            </div>
            <form action="" class="submitDelete" method="post" >
                {!! csrf_field() !!}
                {{ method_field('DELETE') }}
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
                    <button type="submit" class="btn btn-primary">Xóa</button>
                </div>
            </form>
        </div>
    </div>
</div>
 <script>
     function submitDelete(e) {
         var url = $(e).attr('href');
         console.log(url);
         $('.submitDelete').attr('action', url);
         return false;
     }
 </script>
<style>
    .modal-content_1 {
        background: #fff;
    }
</style>

resources/views/admin/partials/slidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <!-- Sidebar user panel -->
        <!-- <div class="user-panel">
            <div class="pull-left image">
                <img src="{{ asset(Auth::user()->image) }}" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
                <p>{{Auth::user()->name}}</p>
                <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
        </div> -->
        @if(!\App\Entity\User::isMember(\Illuminate\Support\Facades\Auth::user()->role))
        <!-- sidebar menu: : style can be found in sidebar.less -->
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header">Menu Chính</li>
            <li class="{{ Request::is('admin/posts', 'admin/posts/create', 'admin/categories') ? 'active' : null }} treeview">
                <a href="">
                    <i class="fa fa-newspaper-o" aria-hidden="true"></i> <span>Quản lý khách hàng</span>
                    <span class="pull-right-container">
                      <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>

                <ul class="treeview-menu">
                    <li class="">
                        <a href="{{route('them_khach_hang')}}"><i class="fa fa-circle-o"></i>Thêm khách hàng</a>
                    </li>
                    <li class="">
                        <a href="{{route('ql_khach_hang')}}"><i class="fa fa-circle-o"></i>Tình trạng khách hàng</a>
                    </li>
                </ul>
            </li>


            <li class="{{ Request::is('admin/posts', 'admin/posts/create', 'admin/categories') ? 'active' : null }} treeview">
                <a href="">
                    <i class="fa fa-newspaper-o" aria-hidden="true"></i> <span>Quản lý Tàu</span>
                    <span class="pull-right-container">
                      <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>

                <ul class="treeview-menu">
                    <li class="">
                        <a href="{{route('them_tau')}}"><i class="fa fa-circle-o"></i>Thêm mới Tàu</a>
                    </li>
                    <li class="">
                        <a href="{{route('ql_tau')}}"><i class="fa fa-circle-o"></i>Phân phối điều chỉnh tàu</a>
                    </li>
                </ul>
            </li>

            <li class="{{ Request::is('admin/posts', 'admin/posts/create', 'admin/categories') ? 'active' : null }} treeview">
                <a href="">
                    <i class="fa fa-newspaper-o" aria-hidden="true"></i> <span>Quản lý Giờ Chạy</span>
                    <span class="pull-right-container">
                      <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>

                <ul class="treeview-menu">
                    <li class="">
                        <a href="{{route('them_gio_tau')}}"><i class="fa fa-circle-o"></i>Thêm Thời gian Tàu Chạy</a>
                    </li>
                    <li class="">
                        <a href="{{route('ql_gio_tau')}}"><i class="fa fa-circle-o"></i>Phân phối điều chỉnh giờ tàu</a>
                    </li>
                </ul>
            </li>
            
            
            <li class="{{ Request::is('admin/posts', 'admin/posts/create', 'admin/categories') ? 'active' : null }} treeview">
                <a href="">
                    <i class="fa fa-newspaper-o" aria-hidden="true"></i> <span>Quản lý Điểm dừng</span>
                    <span class="pull-right-container">
                      <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>

                <ul class="treeview-menu">
                    <li class="">
                        <a href="{{route('them_diem_dung')}}"><i class="fa fa-circle-o"></i>Thêm Điểm dừng</a>
                    </li>
                    <li class="">
                        <a href="{{route('ql_diem_dung')}}"><i class="fa fa-circle-o"></i>Quản lý Điểm dừng</a>
                    </li>
                </ul>
            </li>


            <li class="{{ Request::is('admin/posts', 'admin/posts/create', 'admin/categories') ? 'active' : null }} treeview">
                <a href="">
                    <i class="fa fa-newspaper-o" aria-hidden="true"></i> <span>Quản lý Giao dịch</span>
                    <span class="pull-right-container">
                      <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>

                <ul class="treeview-menu">
                    <li class="">
                        <a href="{{route('ql_thanh_toan')}}"><i class="fa fa-circle-o"></i>Khách hàng đặt vé</a>
                    </li>

                    <!-- <li class="">
                        <a href=""><i class="fa fa-circle-o"></i>Khách hàng đã thành toán </a>
                    </li> -->
                </ul>
            </li>

            <!-- <li class="{{ Request::is('admin/posts', 'admin/posts/create', 'admin/categories') ? 'active' : null }} treeview">
                <a href="">
                    <i class="fa fa-newspaper-o" aria-hidden="true"></i> <span>Quản lý thanh toán</span>
                    <span class="pull-right-container">
                      <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>

                <ul class="treeview-menu">
                    <li class="">
                        <a href=""><i class="fa fa-circle-o"></i>Thanh toán tiền khách hàng</a>
                    </li>
                    <li class="">
                        <a href=""><i class="fa fa-circle-o"></i>Xác nhận thanh toán </a>
                    </li>
                </ul>
            </li> -->

           
            <li class="header">Thành viên</li>
            <li class="{{ Request::is('admin/users', 'admin/users/create') ? 'active' : null }} treeview">
                <a href="{{ route('users.index') }}">
                    <i class="fa fa-wrench" aria-hidden="true"></i> <span>Quản lý thành viên</span>
                    <span class="pull-right-container">
                      <i class="fa fa-angle-left pull-right"></i>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li class="{{ Request::is( 'admin/users' ) ? 'active' : null }}">
                        <a href="{{ route('users.index') }}"><i class="fa fa-circle-o"></i>Tất cả Thành viên</a>
                    </li>
                    <li class="{{ Request::is('admin/users/create') ? 'active' : null }}">
                        <a href="{{ route('users.create') }}"><i class="fa fa-circle-o"></i>Thêm mới thành viên</a>
                    </li>
                </ul>
            </li>
         



            

            

            @endif
         
        </ul>
    </section>
    <!-- /.sidebar -->
</aside>

resources/views/admin/partials/visiable.blade.php
<!-- Modal -->
<div class="modal fade" id="myModalVisiable" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content_1">
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
            </div>
        </div>
    </div>
</div>
<script>
    function visiablePost(e) {
        var postId = $(e).val();
        var visiable = 1;
        if ($(e).prop('checked')) {
            visiable = 0;
        }
        $.ajax({
            type: "GET",
            url: '{!! route('visable_post') !!}',
            data: {
                post_id: postId,
                visiable: visiable
            },
            success: function(data){
                $('#myModalVisiable .modal-body').empty();
                if (visiable == 1) {
                    $('#myModalVisiable .modal-body').append('Ẩn');
                    $('#myModalVisiable').modal('show');

                    return true;
                }
                $('#myModalVisiable .modal-body').append('Hiện');
                $('#myModalVisiable').modal('show');

                return true;
            }
        });
        return true;
    }
</script>
<style>
    .modal-content_1 {
        background: #fff;
    }
</style>